apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ohce
  name: ohce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohce
  strategy: {}
  template:
    metadata:
      labels:
        app: ohce
    spec:
      containers:
        - image: kong/go-echo:latest
          name: ohce
          ports:
            - containerPort: 1025
            - containerPort: 1026
            - containerPort: 1027
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources: {}
