apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
  annotations:
    konghq.com/strip-path: 'true'
spec:
  hostnames:
  -  ohce.chegwin.org
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: ohce
      kind: Service
      port: 1027
