apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohce
  annotations:
    konghq.com/strip-path: 'true'
spec:
  hostnames:
    -  {{ .Values.ingress.hosts.host }}
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: ohce
      kind: Service
      port: 1027
