apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.shortname }}
  name: {{ .Values.shortname }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      app: {{ .Values.shortname }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.shortname }}
    spec:
      containers:
        - image: kong/go-echo:latest
          name: {{ .Values.shortname }}
          ports:
            - containerPort: 1025
            - containerPort: 1026
            - containerPort: 1027
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources: {}
