apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
  annotations:
    konghq.com/strip-path: 'true'
    #bobbins: {{ (index .Values.ingress.hosts 0).host | quote }}
spec:
  hostnames:
    -  {{ (index .Values.ingress.hosts 0).host | quote }}
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: echo
      kind: Service
      port: 1027
