{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    {{- include "nginx-gateway.selectorLabels" . | nindent 4 }}
  ports: # Update the following ports to match your Gateway Listener ports
{{- if .Values.service.ports }}
{{ toYaml .Values.service.ports | indent 2 }}
{{ end }}
{{- end }}
